[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP235x"

[env]
DEFMT_LOG = "debug"

[alias]
golfer-build = "build -p golfer-firmware --target thumbv8m.main-none-eabihf --release"
golfer-run = "run -p golfer-firmware --target thumbv8m.main-none-eabihf --release"
